# Generated by Django 4.1.3 on 2022-11-03 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('debt_or_guns', models.CharField(choices=[('D', 'Debt'), ('G', 'Guns')], max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='player')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(choices=[('HK', 'Hong Kong'), ('SH', 'Shanghai'), ('NS', 'Nagasaki'), ('SG', 'Saigon'), ('MN', 'Manila'), ('SP', 'Singapore'), ('BV', 'Batavia')], default='HK', max_length=2)),
                ('date', models.IntegerField(default=0)),
                ('ship_health', models.IntegerField(default=100)),
                ('ship_size', models.IntegerField(default=60)),
                ('guns', models.IntegerField(default=0)),
                ('cash', models.IntegerField(default=500)),
                ('bank', models.IntegerField(default=0)),
                ('debt', models.IntegerField(default=500)),
                ('opium_ship', models.IntegerField(default=0)),
                ('silk_ship', models.IntegerField(default=0)),
                ('arms_ship', models.IntegerField(default=0)),
                ('general_ship', models.IntegerField(default=0)),
                ('opium_wh', models.IntegerField(default=0)),
                ('silk_wh', models.IntegerField(default=0)),
                ('arms_wh', models.IntegerField(default=0)),
                ('general_wh', models.IntegerField(default=0)),
                ('x_points', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
