# Generated by Django 4.1.3 on 2022-11-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='debt_or_guns',
            field=models.CharField(choices=[('D', 'Debt'), ('G', 'Guns')], default='D', max_length=1),
        ),
    ]
