# Generated by Django 4.1.3 on 2022-11-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_debt_or_guns'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='opium_spot',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='vacant_ship',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='vacant_wh',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='year',
            field=models.IntegerField(default=1860),
        ),
    ]
