# Generated by Django 4.1.3 on 2022-11-04 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gamestate_arms_spot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to='game.game'),
        ),
    ]
